openapi: "3.1.0"
info:
  title: API Title
  version: "1.0"
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
x-user:
  name: User
  description: ユーザ
tags:
  - name: User
    description: ユーザ
  - name: Affiliate
    description: 加盟組織
  - name: Item
    description: 商品
  - name: Order
    description: 注文
  - name: OrderItem
    description: 注文明細
  - name: PurchaseRight
    description: 購入権
servers:
  - url: http://localhost:8000
paths:
  /users:
    get:
      $ref: "./paths/users/index.yml#/get"
      tags:
        - User
    post:
      $ref: "./paths/users/index.yml#/post"
      tags:
        - User
  /users/{user_id}:
    get:
      $ref: "./paths/users/{user_id}/index.yml#/get"
      tags:
        - User
    put:
      $ref: "./paths/users/{user_id}/index.yml#/put"
      tags:
        - User
    delete:
      $ref: "./paths/users/{user_id}/index.yml#/delete"
      tags:
        - User
  /affiliates:
    get:
      $ref: "./paths/affiliates/index.yml#/get"
      tags:
        - Affiliate
    post:
      $ref: "./paths/affiliates/index.yml#/post"
      tags:
        - Affiliate
  /affiliates/{affiliate_id}:
    get:
      $ref: "./paths/affiliates/{affiliate_id}/index.yml#/get"
      tags:
        - Affiliate
    put:
      $ref: "./paths/affiliates/{affiliate_id}/index.yml#/put"
      tags:
        - Affiliate
    delete:
      $ref: "./paths/affiliates/{affiliate_id}/index.yml#/delete"
      tags:
        - Affiliate
  /items:
    get:
      $ref: "./paths/items/index.yml#/get"
      tags:
        - Item
    post:
      $ref: "./paths/items/index.yml#/post"
      tags:
        - Item
  /items/{item_id}:
    get:
      $ref: "./paths/items/{item_id}/index.yml#/get"
      tags:
        - Item
    put:
      $ref: "./paths/items/{item_id}/index.yml#/put"
      tags:
        - Item
    delete:
      $ref: "./paths/items/{item_id}/index.yml#/delete"
      tags:
        - Item
  /orders:
    get:
      $ref: "./paths/orders/index.yml#/get"
      tags:
        - Order
    post:
      $ref: "./paths/orders/index.yml#/post"
      tags:
        - Order
  /orders/{order_id}:
    get:
      $ref: "./paths/orders/{order_id}/index.yml#/get"
      tags:
        - Order
    put:
      $ref: "./paths/orders/{order_id}/index.yml#/put"
      tags:
        - Order
    delete:
      $ref: "./paths/orders/{order_id}/index.yml#/delete"
      tags:
        - Order
  /orders/{order_id}/items:
    get:
      $ref: "./paths/order_items/index.yml#/get"
      tags:
        - OrderItem
    post:
      $ref: "./paths/order_items/index.yml#/post"
      tags:
        - OrderItem
  /orders/{order_id}/items/{order_item_id}:
    get:
      $ref: "./paths/order_items/{order_item_id}/index.yml#/get"
      tags:
        - OrderItem
    put:
      $ref: "./paths/order_items/{order_item_id}/index.yml#/put"
      tags:
        - OrderItem
    delete:
      $ref: "./paths/order_items/{order_item_id}/index.yml#/delete"
      tags:
        - OrderItem
  /purchase_rights:
    get:
      $ref: "./paths/purchase_rights/index.yml#/get"
      tags:
        - PurchaseRight
    post:
      $ref: "./paths/purchase_rights/index.yml#/post"
      tags:
        - PurchaseRight
  /purchase_rights/{purchase_right_id}:
    get:
      $ref: "./paths/purchase_rights/{purchase_right_id}/index.yml#/get"
      tags:
        - PurchaseRight
    put:
      $ref: "./paths/purchase_rights/{purchase_right_id}/index.yml#/put"
      tags:
        - PurchaseRight
    delete:
      $ref: "./paths/purchase_rights/{purchase_right_id}/index.yml#/delete"
      tags:
        - PurchaseRight
# openalchemyのために少なくともテーブルクラスは列挙しないといけない
# 名称競合回避のためここでは先頭に"_"をつける
components:
  schemas:
    User:
      $ref: "./components/schemas/user.yml#/User"
    Affiliate:
      $ref: "./components/schemas/affiliate.yml#/Affiliate"
    Item:
      $ref: "./components/schemas/item.yml#/Item"
    Order:
      $ref: "./components/schemas/order.yml#/Order"
    OrderItem:
      $ref: "./components/schemas/order_item.yml#/OrderItem"
    PurchaseRight:
      $ref: "./components/schemas/purchase_right.yml#/PurchaseRight"
    CreateUserRequest:
      $ref: "./components/schemas/user.yml#/CreateUserRequest"
    UpdateUserRequest:
      $ref: "./components/schemas/user.yml#/UpdateUserRequest"
    CreateAffiliateRequest:
      $ref: "./components/schemas/affiliate.yml#/CreateAffiliateRequest"
    UpdateAffiliateRequest:
      $ref: "./components/schemas/affiliate.yml#/UpdateAffiliateRequest"
    CreateItemRequest:
      $ref: "./components/schemas/item.yml#/CreateItemRequest"
    UpdateItemRequest:
      $ref: "./components/schemas/item.yml#/UpdateItemRequest"
    CreateOrderRequest:
      $ref: "./components/schemas/order.yml#/CreateOrderRequest"
    UpdateOrderRequest:
      $ref: "./components/schemas/order.yml#/UpdateOrderRequest"
    CreateOrderItemRequest:
      $ref: "./components/schemas/order_item.yml#/CreateOrderItemRequest"
    UpdateOrderItemRequest:
      $ref: "./components/schemas/order_item.yml#/UpdateOrderItemRequest"
    CreatePurchaseRightRequest:
      $ref: "./components/schemas/purchase_right.yml#/CreatePurchaseRightRequest"
    UpdatePurchaseRightRequest:
      $ref: "./components/schemas/purchase_right.yml#/UpdatePurchaseRightRequest"
