# openapi: "3.0.2"
openapi: "3.1.0"
info:
  title: API Title
  version: "1.0"
tags:
  - name: User
  - name: Affiliate
  - name: Item
  - name: Order
  - name: OrderItem
  - name: PurchaseRight
servers:
  - url: http://localhost:8000
paths:
  /users:
    get:
      tags:
        - User
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
    post:
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/CreateUserRequest"
      responses:
        "200":
          description: Success
  /users/{user_id}:
    get:
      tags:
        - User
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/User"
    put:
      tags:
        - User
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/UpdateUserRequest"
      responses:
        "200":
          description: Success
    delete:
      tags:
        - User
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Success
  /affiliates:
    get:
      tags:
        - Affiliate
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Affiliate"
    post:
      tags:
        - Affiliate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/CreateAffiliateRequest"
      responses:
        "200":
          description: Success
  /affiliates/{affiliate_id}:
    get:
      tags:
        - Affiliate
      parameters:
        - in: path
          name: affiliate_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Affiliate"
    put:
      tags:
        - Affiliate
      parameters:
        - in: path
          name: affiliate_id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/UpdateAffiliateRequest"
      responses:
        "200":
          description: Success
    delete:
      tags:
        - Affiliate
      parameters:
        - in: path
          name: affiliate_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Success
  /items:
    get:
      tags:
        - Item
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
    post:
      tags:
        - Item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/CreateItemRequest"
      responses:
        "200":
          description: Success
  /items/{item_id}:
    get:
      tags:
        - Item
      parameters:
        - in: path
          name: item_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Item"
    put:
      tags:
        - Item
      parameters:
        - in: path
          name: item_id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/UpdateItemRequest"
      responses:
        "200":
          description: Success
    delete:
      tags:
        - Item
      parameters:
        - in: path
          name: item_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Success
  /orders:
    get:
      tags:
        - Order
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
    post:
      tags:
        - Order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/CreateOrderRequest"
      responses:
        "200":
          description: Success
  /orders/{order_id}:
    get:
      tags:
        - Order
      parameters:
        - in: path
          name: order_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Order"
    put:
      tags:
        - Order
      parameters:
        - in: path
          name: order_id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/UpdateOrderRequest"
      responses:
        "200":
          description: Success
    delete:
      tags:
        - Order
      parameters:
        - in: path
          name: order_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Success
  /orders/{order_id}/items:
    get:
      tags:
        - OrderItem
      parameters:
        - in: path
          name: order_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrderItem"
    post:
      tags:
        - OrderItem
      parameters:
        - in: path
          name: order_id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/CreateOrderItemRequest"
      responses:
        "200":
          description: Success
  /orders/{order_id}/items/{order_item_id}:
    get:
      tags:
        - OrderItem
      parameters:
        - in: path
          name: order_id
          required: true
          schema:
            type: string
            format: uuid
        - in: path
          name: order_item_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/OrderItem"
    put:
      tags:
        - OrderItem
      parameters:
        - in: path
          name: order_id
          required: true
          schema:
            type: string
            format: uuid
        - in: path
          name: order_item_id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/UpdateOrderItemRequest"
      responses:
        "200":
          description: Success
    delete:
      tags:
        - OrderItem
      parameters:
        - in: path
          name: order_id
          required: true
          schema:
            type: string
            format: uuid
        - in: path
          name: order_item_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Success
  /purchase_rights:
    get:
      tags:
        - PurchaseRight
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PurchaseRight"
    post:
      tags:
        - PurchaseRight
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/CreatePurchaseRightRequest"
      responses:
        "200":
          description: Success
  /purchase_rights/{purchase_right_id}:
    get:
      tags:
        - PurchaseRight
      parameters:
        - in: path
          name: purchase_right_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/PurchaseRight"
    put:
      tags:
        - PurchaseRight
      parameters:
        - in: path
          name: purchase_right_id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/UpdatePurchaseRightRequest"
      responses:
        "200":
          description: Success
    delete:
      tags:
        - PurchaseRight
      parameters:
        - in: path
          name: purchase_right_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Success

# openalchemyのために少なくともテーブルクラスは列挙しないといけない
# 名称競合回避のためここでは先頭に"_"をつける
components:
  schemas:
    User:
      $ref: "./schemas/user.yml#/schemas/User"
    Affiliate:
      $ref: "./schemas/affiliate.yml#/schemas/Affiliate"
    Item:
      $ref: "./schemas/item.yml#/schemas/Item"
    Order:
      $ref: "./schemas/order.yml#/schemas/Order"
    OrderItem:
      $ref: "./schemas/order_item.yml#/schemas/OrderItem"
    PurchaseRight:
      $ref: "./schemas/purchase_right.yml#/schemas/PurchaseRight"
    CreateUserRequest:
      $ref: "./schemas/user.yml#/schemas/CreateUserRequest"
    UpdateUserRequest:
      $ref: "./schemas/user.yml#/schemas/UpdateUserRequest"
    CreateAffiliateRequest:
      $ref: "./schemas/affiliate.yml#/schemas/CreateAffiliateRequest"
    UpdateAffiliateRequest:
      $ref: "./schemas/affiliate.yml#/schemas/UpdateAffiliateRequest"
    CreateItemRequest:
      $ref: "./schemas/item.yml#/schemas/CreateItemRequest"
    UpdateItemRequest:
      $ref: "./schemas/item.yml#/schemas/UpdateItemRequest"
    CreateOrderRequest:
      $ref: "./schemas/order.yml#/schemas/CreateOrderRequest"
    UpdateOrderRequest:
      $ref: "./schemas/order.yml#/schemas/UpdateOrderRequest"
    CreateOrderItemRequest:
      $ref: "./schemas/order_item.yml#/schemas/CreateOrderItemRequest"
    UpdateOrderItemRequest:
      $ref: "./schemas/order_item.yml#/schemas/UpdateOrderItemRequest"
    CreatePurchaseRightRequest:
      $ref: "./schemas/purchase_right.yml#/schemas/CreatePurchaseRightRequest"
    UpdatePurchaseRightRequest:
      $ref: "./schemas/purchase_right.yml#/schemas/UpdatePurchaseRightRequest"
