openapi: "3.1.0"
info:
  title: API Title
  version: "1.0"
tags:
  - name: User
  - name: Affiliate
  - name: Item
  - name: Order
  - name: OrderItem
  - name: PurchaseRight
servers:
  - url: http://localhost:8000

paths:
  /users:
    $ref: "./paths/users/index.yml"
  /users/{user_id}:
    $ref: "./paths/users/{user_id}/index.yml"
  /affiliates:
    $ref: "./paths/affiliates/index.yml"
  /affiliates/{affiliate_id}:
    $ref: "./paths/affiliates/{affiliate_id}/index.yml"
  /items:
    $ref: "./paths/items/index.yml"
  /items/{item_id}:
    $ref: "./paths/items/{item_id}/index.yml"
  /orders:
    $ref: "./paths/orders/index.yml"
  /orders/{order_id}:
    $ref: "./paths/orders/{order_id}/index.yml"
  /orders/{order_id}/items:
    $ref: "./paths/order_items/index.yml"
  /orders/{order_id}/items/{order_item_id}:
    $ref: "./paths/order_items/{order_item_id}/index.yml"
  /purchase_rights:
    $ref: "./paths/purchase_rights/index.yml"
  /purchase_rights/{purchase_right_id}:
    $ref: "./paths/purchase_rights/{purchase_right_id}/index.yml"

# openalchemyのために少なくともテーブルクラスは列挙しないといけない
# 名称競合回避のためここでは先頭に"_"をつける
components:
  schemas:
    User:
      $ref: "./schemas/user.yml#/schemas/User"
    Affiliate:
      $ref: "./schemas/affiliate.yml#/schemas/Affiliate"
    Item:
      $ref: "./schemas/item.yml#/schemas/Item"
    Order:
      $ref: "./schemas/order.yml#/schemas/Order"
    OrderItem:
      $ref: "./schemas/order_item.yml#/schemas/OrderItem"
    PurchaseRight:
      $ref: "./schemas/purchase_right.yml#/schemas/PurchaseRight"
    CreateUserRequest:
      $ref: "./schemas/user.yml#/schemas/CreateUserRequest"
    UpdateUserRequest:
      $ref: "./schemas/user.yml#/schemas/UpdateUserRequest"
    CreateAffiliateRequest:
      $ref: "./schemas/affiliate.yml#/schemas/CreateAffiliateRequest"
    UpdateAffiliateRequest:
      $ref: "./schemas/affiliate.yml#/schemas/UpdateAffiliateRequest"
    CreateItemRequest:
      $ref: "./schemas/item.yml#/schemas/CreateItemRequest"
    UpdateItemRequest:
      $ref: "./schemas/item.yml#/schemas/UpdateItemRequest"
    CreateOrderRequest:
      $ref: "./schemas/order.yml#/schemas/CreateOrderRequest"
    UpdateOrderRequest:
      $ref: "./schemas/order.yml#/schemas/UpdateOrderRequest"
    CreateOrderItemRequest:
      $ref: "./schemas/order_item.yml#/schemas/CreateOrderItemRequest"
    UpdateOrderItemRequest:
      $ref: "./schemas/order_item.yml#/schemas/UpdateOrderItemRequest"
    CreatePurchaseRightRequest:
      $ref: "./schemas/purchase_right.yml#/schemas/CreatePurchaseRightRequest"
    UpdatePurchaseRightRequest:
      $ref: "./schemas/purchase_right.yml#/schemas/UpdatePurchaseRightRequest"
