version: "3"

services:
  api:
    image: sw_back_api_dev
    container_name: sw_back_api_dev
    build:
      context: ./docker/api
      dockerfile: Dockerfile
      target: development
    user: root # non-rootだとマウントしたファイル操作できないため
    tty: true
    volumes:
      - ./app:/home/app:cached
      - ./db:/home/db:cached
      - ./docs:/home/docs:cached # for migrate
      - ./templates:/home/templates:cached # for generate
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf:cached
    ports:
      - 8000:8000
    env_file:
      - .env.development
    depends_on:
      - db
    command: uvicorn main:app --reload --host 0.0.0.0

  db:
    image: sw_back_db_dev
    container_name: sw_back_db_dev
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./log/db:/var/log/mysql:cached
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf:cached
    env_file:
      - .env.development
