"""create tables

Revision ID: 3e6646781ec0
Revises: 
Create Date: 2023-05-06 12:59:22.789747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6646781ec0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('postcode', sa.String(length=8), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('tel', sa.String(length=13), nullable=False),
    sa.Column('fax', sa.String(length=13), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('Now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('Now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('tel', sa.String(length=13), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('Now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('Now()'), nullable=False),
    sa.Column('affiliate_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('affiliates')
    # ### end Alembic commands ###
