"""create tables

Revision ID: b40d0757155f
Revises: 
Create Date: 2023-05-07 05:00:17.922522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b40d0757155f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('postcode', sa.String(length=8), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('tel', sa.String(length=13), nullable=False),
    sa.Column('fax', sa.String(length=13), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('Now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('Now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('img_src', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('sales_start', sa.DateTime(), nullable=True),
    sa.Column('sales_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('Now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('Now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('tel', sa.String(length=13), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('Now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('Now()'), nullable=False),
    sa.Column('affiliate_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('postcode', sa.String(length=8), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('approved_flag', sa.Boolean(), nullable=False),
    sa.Column('affiliate_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('items')
    op.drop_table('affiliates')
    # ### end Alembic commands ###
