# generated by fastapi-codegen:
#   filename:  openapi.yml
#   timestamp: 2023-05-04T12:43:39+00:00

from __future__ import annotations

from fastapi import APIRouter

from ..dependencies import *

router = APIRouter(tags=['Affiliate'])


@router.get('/affiliates', response_model=List[Affiliate], tags=['Affiliate'])
def get_affiliates() -> List[Affiliate]:
    pass


@router.post('/affiliates', response_model=str, tags=['Affiliate'])
def post_affiliates(body: AffiliatesPostRequest) -> str:
    pass
