# generated by fastapi-codegen:
#   filename:  openapi.yml
#   timestamp: 2023-05-04T12:43:39+00:00

from __future__ import annotations

from typing import List

from .models import Affiliate, AffiliatesPostRequest, User, UsersPostRequest
