# generated by fastapi-codegen:
#   filename:  openapi.yml
#   timestamp: 2023-05-04T12:53:09+00:00

from __future__ import annotations

from fastapi import FastAPI

from .routers import affiliate, user

app = FastAPI(
    title='API Title',
    version='1.0',
    servers=[{'url': 'https://api.server.test/v1'}],
)

app.include_router(affiliate.router)
app.include_router(user.router)


@app.get("/")
async def root():
    return {"message": "Gateway of the App"}
