openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
tags:
  - name: User
  - name: Affiliate
servers:
  - url: https://api.server.test/v1
paths:
  /users:
    get:
      tags:
        - User
      responses:
        '200':
          description: ユーザ一覧の取得
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/User'
    post:
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  maxLength: 255
                  description: 名
                  example: 太郎
                last_name:
                  type: string
                  maxLength: 255
                  description: 姓
                  example: 山田
                tel:
                  type: string
                  maxLength: 255
                  description: 電話番号
                  example: 000-0000-0000
                email:
                  type: string
                  maxLength: 255
                  description: メールアドレス
                  example: sample@sample.com
              required:
                - first_name
                - last_name
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string

  /affiliates:
    get:
      tags:
        - Affiliate
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/Affiliate'
    post:
      tags:
        - Affiliate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  maxLength: 255
                  description: 組織名
                  example: 株式会社サンプル
                postcode:
                  type: string
                  maxLength: 8
                  description: 郵便番号
                  example: 000-0000
                address:
                  type: string
                  maxLength: 255
                  description: 住所
                  example: 静岡県沼津市上土町36
                tel:
                  type: string
                  maxLength: 13
                  description: 電話番号
                  example: 000-0000-0000
                fax:
                  type: string
                  maxLength: 13
                  description: FAX番号
                  example: 000-0000-0000
                email:
                  type: string
                  maxLength: 255
                  description: メールアドレス
                  example: sample@sample.com
              required:
                - name
                - postcode
                - address
                - tel
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    User:
      type: object
      description: 担当者
      x-tablename: users
      properties:
        id:
          type: string
          maxLength: 36
          format: uuid
          description: ユーザID
          x-primary-key: true
        first_name:
          type: string
          maxLength: 255
          description: 名
          example: 太郎
        last_name:
          type: string
          maxLength: 255
          description: 姓
          example: 山田
        tel:
          type: string
          maxLength: 13
          description: 電話番号
          example: 000-0000-0000
        email:
          type: string
          maxLength: 13
          description: メールアドレス
          example: sample@sample.com
        created_at:
          type: string
          format: date-time
          description: 作成日
        updated_at:
          type: string
          format: date-time
          description: 更新日
      required:
        - first_name
        - last_name
        - tel
        - created_at
        - updated_at
    Affiliate:
      type: object
      description: 加盟組織
      x-tablename: affiliates
      properties:
        id:
          type: string
          maxLength: 36
          format: uuid
          description: 加盟組織ID
          x-primary-key: true
        name:
          type: string
          maxLength: 255
          description: 組織名
          example: 株式会社サンプル
        postcode:
          type: string
          maxLength: 8
          description: 郵便番号
          example: 000-0000
        address:
          type: string
          maxLength: 255
          description: 住所
          example: 静岡県沼津市上土町36
        tel:
          type: string
          maxLength: 13
          description: 電話番号
          example: 000-0000-0000
        fax:
          type: string
          maxLength: 13
          description: FAX番号
          example: 000-0000-0000
        email:
          type: string
          maxLength: 255
          description: メールアドレス
          example: sample@sample.com
        created_at:
          type: string
          format: date-time
          description: 作成日
        updated_at:
          type: string
          format: date-time
          description: 更新日
        user:
          $ref: "#/components/schemas/User"
      required:
        - name
        - postcode
        - address
        - tel
        - created_at
        - updated_at